### PR TITLE
F1 score

### PR DESCRIPTION
**Pull request by tejalkul**
Added a F1 score metrics. The code may not be general to all cases. It was specific to my case.

### CODE REVIEW

**Comment by krafczyk** [comment]
Hey Tejal,

Can you run the flake and test suite? have a look at the `tests.sh` and `flake.sh`. These scripts run the test suite and grammar checking. I need to write some documentation about this so its clear what to do.

**Comment by tejalkul** [comment]
Sure I will do that

**Comment by tejalkul** [comment]
I have changed the spacing of scalar.py so that flake.sh runs without any errors.
After running tests.sh I got the following results:

=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.9.12, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /home/tejalk00/REU_Project/DRYML_Clone/DRYML
plugins: anyio-3.6.1, cov-4.0.0
collected 234 items                                                                                                                                                                                                

tests/test_collections.py ..............                                                                                                                                                                     [  5%]
tests/test_config.py ........                                                                                                                                                                                [  9%]
tests/test_contexts.py ...                                                                                                                                                                                   [ 10%]
tests/test_data.py ............................................................                                                                                                                              [ 36%]
tests/test_data_tf.py ........................                                                                                                                                                               [ 46%]
tests/test_dry_trainable.py ......                                                                                                                                                                           [ 49%]
tests/test_end_to_end.py ...........................                                                                                                                                                         [ 60%]
tests/test_file_intermediary.py ......                                                                                                                                                                       [ 63%]
tests/test_object.py .....x..............................                                                                                                                                                    [ 78%]
tests/test_repo.py ......x....................                                                                                                                                                               [ 90%]
tests/test_selector.py ..............                                                                                                                                                                        [ 96%]
tests/test_tf.py ....                                                                                                                                                                                        [ 97%]
tests/test_utils.py ....                                                                                                                                                                                     [ 99%]
tests/test_workflows.py .                                                                                                                                                                                    [100%]

================================================================================================= warnings summary =================================================================================================
/home/tejalk00/REU_Project/myenv_1.6/lib/python3.9/site-packages/flatbuffers/compat.py:19
  /home/tejalk00/REU_Project/myenv_1.6/lib/python3.9/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html

<h4>
---------- coverage: platform linux, python 3.9.12-final-0 -----------  </br>
Name                                    Stmts   Miss  Cover  </br>
-----------------------------------------------------------  </br>
src/dryml/__init__.py                      10      0   100%  </br>
src/dryml/collections.py                   50      3    94%  </br>
src/dryml/config.py                       743    162    78%  </br>
src/dryml/context/__init__.py               3      0   100%  </br>
src/dryml/context/context_tracker.py      364    104    71%  </br>
src/dryml/context/process.py              374    196    48%  </br>
src/dryml/context/tf/__init__.py            2      0   100%  </br>
src/dryml/context/tf/context.py            55     26    53%  </br>
src/dryml/context/torch/__init__.py         2      0   100%  </br>
src/dryml/context/torch/context.py         23      4    83%  </br>
src/dryml/data/__init__.py                  5      0   100%  </br>
src/dryml/data/dataset.py                 109     31    72%  </br>
src/dryml/data/image.py                    12     12     0%  </br>
src/dryml/data/numpy_dataset.py           164     31    81%  </br>
src/dryml/data/pandas/__init__.py           2      2     0%  </br>
src/dryml/data/pandas/prep_funcs.py        26     26     0%  </br>
src/dryml/data/tf/__init__.py               2      0   100%  </br>
src/dryml/data/tf/dataset.py               62     20    68%  </br>
src/dryml/data/torch/__init__.py            3      0   100%  </br>
src/dryml/data/torch/dataset.py           116     43    63%  </br>
src/dryml/data/torch/transforms.py         32     12    62%  </br>
src/dryml/data/transforms.py              158     68    57%  </br>
src/dryml/data/util.py                    145     24    83%  </br>
src/dryml/file_intermediary.py             82     15    82%  </br>
src/dryml/metrics/__init__.py               2      0   100%  </br>
src/dryml/metrics/scalar.py                62     33    47%  </br>
src/dryml/models/__init__.py                7      0   100%  </br>
src/dryml/models/component.py              12      2    83%  </br>
src/dryml/models/model.py                   7      1    86%  </br>
src/dryml/models/pipe.py                   36      6    83%  </br>
src/dryml/models/sklearn/__init__.py        2      0   100%  </br>
src/dryml/models/sklearn/base.py           76      7    91%  </br>
src/dryml/models/tf/__init__.py             4      0   100%  </br>
src/dryml/models/tf/base.py                32      3    91% </br>
src/dryml/models/tf/keras/__init__.py       2      0   100%  </br>
src/dryml/models/tf/keras/base.py         324    159    51%  </br>
src/dryml/models/tf/utils.py               13      6    54%  </br>
src/dryml/models/torch/__init__.py          3      0   100%  </br>
src/dryml/models/torch/base.py             84     34    60%  </br>
src/dryml/models/torch/generic.py         212     80    62%  </br>
src/dryml/models/train_spec.py             44     27    39%  </br>
src/dryml/models/trainable.py              30      2    93%  </br>
src/dryml/models/utils.py                  11      7    36%  </br>
src/dryml/models/xgb/__init__.py            2      0   100%  </br>
src/dryml/models/xgb/base.py               44      2    95%  </br>
src/dryml/object.py                       540    113    79%  </br>
src/dryml/ray/__init__.py                   2      2     0%  </br>
src/dryml/ray/tune.py                     172    172     0%  </br>
src/dryml/repo.py                         414    131    68%  </br>
src/dryml/save_cache.py                    15      1    93%  </br>
src/dryml/selector.py                     177     31    82%  </br>
src/dryml/utils.py                        261    130    50%  </br>
src/dryml/vis/__init__.py                   2      2     0%  </br>
src/dryml/vis/scalar.py                    22     22     0%  </br>
src/dryml/workshop.py                      15      5    67%  </br>
-----------------------------------------------------------  </br>
TOTAL                                    5173   1757    66%

</h4>

============================================================================== 232 passed, 2 xfailed, 1 warning in 485.11s (0:08:05) ===============================================================================

**Comment by krafczyk** [comment]
I have only one more minor formatting issue to handle, Implementation seems fine to me, so I'm ready to merge this once the comment I made is addressed. Please run the tests.sh and flake.sh again as well.

**Comment by krafczyk** [comment]
Hey @tejalkul , I updated the test infrastructure and made a minor change regarding serialization/deserialization, can you implement the format change I mentioned, rebase and if tests pass, I'll merge this.

**Comment by tejalkul** [comment]
Yeah sure.

**Comment by tejalkul** [comment]
After running the tests I got this output

=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.9.12, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /home/tejalk00/REU_Project/DRYML_Clone/DRYML
plugins: anyio-3.6.1, cov-4.0.0
collected 234 items                                                                                                                                                                                                

tests/test_collections.py ..............                                                                                                                                                                     [  5%]
tests/test_config.py ........                                                                                                                                                                                [  9%]
tests/test_contexts.py ...                                                                                                                                                                                   [ 10%]
tests/test_data.py ............................................................                                                                                                                              [ 36%]
tests/test_data_tf.py ........................                                                                                                                                                               [ 46%]
tests/test_dry_trainable.py ......                                                                                                                                                                           [ 49%]
tests/test_end_to_end.py ...........................                                                                                                                                                         [ 60%]
tests/test_file_intermediary.py ......                                                                                                                                                                       [ 63%]
tests/test_object.py .....x..............................                                                                                                                                                    [ 78%]
tests/test_repo.py ......x....................                                                                                                                                                               [ 90%]
tests/test_selector.py ..............                                                                                                                                                                        [ 96%]
tests/test_tf.py ....                                                                                                                                                                                        [ 97%]
tests/test_utils.py ....                                                                                                                                                                                     [ 99%]
tests/test_workflows.py .                                                                                                                                                                                    [100%]

================================================================================================= warnings summary =================================================================================================
/home/tejalk00/REU_Project/myenv_1.6/lib/python3.9/site-packages/flatbuffers/compat.py:19
  /home/tejalk00/REU_Project/myenv_1.6/lib/python3.9/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html

<h4>---------- coverage: platform linux, python 3.9.12-final-0 ----------- <br>
Name                                    Stmts   Miss  Cover <br>
-----------------------------------------------------------<br>
src/dryml/__init__.py                      10      0   100%  <br>
src/dryml/collections.py                   50      3    94%  <br>
src/dryml/config.py                       715    157    78%  <br>
src/dryml/context/__init__.py               3      0   100%   <br>
src/dryml/context/context_tracker.py      364    104    71%   <br>
src/dryml/context/process.py              374    196    48%  <br>
src/dryml/context/tf/__init__.py            2      0   100%   <br> 
src/dryml/context/tf/context.py            55     26    53%  <br>
src/dryml/context/torch/__init__.py         2      0   100%   <br>
src/dryml/context/torch/context.py         23      4    83%   <br>
src/dryml/data/__init__.py                  5      0   100%  <br>
src/dryml/data/dataset.py                 109     31    72%    <br>
src/dryml/data/image.py                    12     12     0%  <br>
src/dryml/data/numpy_dataset.py           164     31    81%   <br>
src/dryml/data/pandas/__init__.py           2      2     0%   <br>
src/dryml/data/pandas/prep_funcs.py        26     26     0%   <br>
src/dryml/data/tf/__init__.py               2      0   100%   <br>
src/dryml/data/tf/dataset.py               62     20    68%  <br>
src/dryml/data/torch/__init__.py            3      0   100%  <br>
src/dryml/data/torch/dataset.py           116     43    63%  <br>
src/dryml/data/torch/transforms.py         32     12    62%  <br>
src/dryml/data/transforms.py              158     68    57%  <br>
src/dryml/data/util.py                    145     24    83%   <br>
src/dryml/file_intermediary.py             82     15    82%   <br>
src/dryml/metrics/__init__.py               2      0   100%   <br>
src/dryml/metrics/scalar.py                62     33    47%   <br>
src/dryml/models/__init__.py                7      0   100%   <br>
src/dryml/models/component.py              12      2    83%   <br>
src/dryml/models/model.py                   7      1    86%  <br>
src/dryml/models/pipe.py                   36      6    83%   <br>
src/dryml/models/sklearn/__init__.py        2      0   100%   <br>
src/dryml/models/sklearn/base.py           76      7    91%   <br>
src/dryml/models/tf/__init__.py             4      0   100%   <br>
src/dryml/models/tf/base.py                32      3    91%  <br>
src/dryml/models/tf/keras/__init__.py       2      0   100%  <br>
src/dryml/models/tf/keras/base.py         324    159    51%  <br>
src/dryml/models/tf/utils.py               13      6    54%  <br>
src/dryml/models/torch/__init__.py          3      0   100%  <br>
src/dryml/models/torch/base.py             84     34    60%   <br>
src/dryml/models/torch/generic.py         212     80    62%  <br>
src/dryml/models/train_spec.py             44     27    39%  <br>
src/dryml/models/trainable.py              30      2    93%   <br>
src/dryml/models/utils.py                  11      7    36%   <br>
src/dryml/models/xgb/__init__.py            2      0   100%   <br>
src/dryml/models/xgb/base.py               44      2    95%   <br>
src/dryml/object.py                       526    101    81%   <br>
src/dryml/ray/__init__.py                   2      2     0%    <br>
src/dryml/ray/tune.py                     172    172     0%   <br>
src/dryml/repo.py                         415    132    68%   <br>
src/dryml/save_cache.py                    15      1    93%   <br>
src/dryml/selector.py                     177     31    82%   <br>
src/dryml/utils.py                        337    184    45%   <br>
src/dryml/vis/__init__.py                   2      2     0%   <br>
src/dryml/vis/scalar.py                    22     22     0%  <br>
src/dryml/workshop.py                      15      5    67%  <br>
-----------------------------------------------------------  <br>
TOTAL                                    5208   1795    66%   <br>

============================================================================== 232 passed, 2 xfailed, 1 warning in 592.86s (0:09:52) ===============================================================================</h4>

**Pull request merged**
